# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Nuclear Science parameters
mod_version=0.7.1-0
mod_id=nuclearscience
mod_group_id=nuclearscience
mod_name=Nuclear Science

# Other Parameters
mod_license=All Rights Reserved
mod_authors=aurilisdev, skip999
mod_credits=Thanks to all contributors. Brazil lang key by FITFC. Russian lang key by Quarkrus
mod_description=A continuation of Atomic Science expanding on its core principles with a unique spin

# Version parameters
minecraft_version=1.21.1
minecraft_version_range=[1.21,1.21.1)
neo_version=21.1.72
neo_version_range=[21.0.0-beta,)
loader_version_range=[4,)


# Dependency parameters 
jei_version=19.21.0.246

# Parchment parameters
neogradle.subsystems.parchment.minecraftVersion=1.21
neogradle.subsystems.parchment.mappingsVersion=2024.07.28
