package nuclearscience.api.turbine;

/**
 * 
 * A simple wrapper interface that allows different blocks to receive steam generated by reactors
 * 
 * @author skip999
 *
 */
public interface ISteamReceiver {

	/**
	 * 
	 * @param temperature: The temperature of the steam
	 * @param amount:      The amount of steam
	 * @return How much steam was accepted
	 */
	public int receiveSteam(int temperature, int amount);

	public boolean isStillValid();

}
